// Regenerate src/generated/psl-rules.js from a pinned Public Suffix List.
//
//   node scripts/build-psl.mjs
//
// Downloads public_suffix_list.dat at a fixed commit, refuses to continue
// unless its SHA-256 matches the pin below, and writes a compact module of
// rules. The generated module is committed so normal builds never need the
// network. The list is MPL-2.0; see src/generated/PSL-LICENSE.txt.
import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const COMMIT = "3929462652695bad04f0a27afb600974014a3c8b";
const SHA256 = "2919eb9803c91a3f73a507cc6fedc934de005543c22c4016f72e3343de5dd6e7";
const URL_ = `https://raw.githubusercontent.com/publicsuffix/list/${COMMIT}/public_suffix_list.dat`;
const OUT = fileURLToPath(new URL("../src/generated/psl-rules.js", import.meta.url));

const response = await fetch(URL_, { redirect: "error" });
if (!response.ok) throw new Error(`download failed: HTTP ${response.status}`);
const body = Buffer.from(await response.arrayBuffer());
const digest = createHash("sha256").update(body).digest("hex");
if (digest !== SHA256) throw new Error(`SHA-256 mismatch: got ${digest}`);

const rules = body
  .toString("utf8")
  .split("\n")
  .map((line) => line.trim().split(/\s/)[0])
  .filter((line) => line && !line.startsWith("//"))
  .map((rule) => {
    // Store rules in ASCII (punycode) form, matching URL.hostname output.
    const prefix = rule.startsWith("!") ? "!" : rule.startsWith("*.") ? "*." : "";
    const name = rule.slice(prefix.length);
    return prefix + new URL(`http://${name}`).hostname;
  });

const header = `// GENERATED by scripts/build-psl.mjs - do not edit.
// Public Suffix List @ ${COMMIT} (sha256 ${SHA256}), MPL-2.0.
`;
await writeFile(OUT, `${header}export const PSL_COMMIT = "${COMMIT}";\nexport const RULES = ${JSON.stringify(rules.join(","))}.split(",");\n`);
console.log(`wrote ${rules.length} rules to ${OUT}`);
